'use strict';
const {
    Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
    class riskdf extends Model {
        static associate(models) {
        }
    }
    riskdf.init({
        closetime: DataTypes.STRING,
        btccloseprice: DataTypes.STRING,
        btcudpil: DataTypes.TEXT,
        btcudpim: DataTypes.TEXT,
        btcudpis: DataTypes.TEXT,
        btcmbi: DataTypes.TEXT,
        btctci: DataTypes.TEXT,
        btctcicv: DataTypes.TEXT,
        btcmdccv: DataTypes.TEXT,
        btcmdcdp: DataTypes.TEXT,
        btcvolume: DataTypes.TEXT,
        btcmc: DataTypes.TEXT,
        btccs: DataTypes.TEXT,

        ethcloseprice: DataTypes.STRING,
        ethudpil: DataTypes.TEXT,
        ethudpim: DataTypes.TEXT,
        ethudpis: DataTypes.TEXT,
        ethmbi: DataTypes.TEXT,
        ethtci: DataTypes.TEXT,
        ethtcicv: DataTypes.TEXT,
        ethmdccv: DataTypes.TEXT,
        ethmdcdp: DataTypes.TEXT,
        ethvolume: DataTypes.TEXT,
        ethmc: DataTypes.TEXT,
        ethcs: DataTypes.TEXT,

        adacloseprice: DataTypes.STRING,
        adaudpil: DataTypes.TEXT,
        adaudpim: DataTypes.TEXT,
        adaudpis: DataTypes.TEXT,
        adambi: DataTypes.TEXT,
        adatci: DataTypes.TEXT,
        adatcicv: DataTypes.TEXT,
        adamdccv: DataTypes.TEXT,
        adamdcdp: DataTypes.TEXT,
        adavolume: DataTypes.TEXT,
        adamc: DataTypes.TEXT,
        adacs: DataTypes.TEXT,

        dotcloseprice: DataTypes.STRING,
        dotudpil: DataTypes.TEXT,
        dotudpim: DataTypes.TEXT,
        dotudpis: DataTypes.TEXT,
        dotmbi: DataTypes.TEXT,
        dottci: DataTypes.TEXT,
        dottcicv: DataTypes.TEXT,
        dotmdccv: DataTypes.TEXT,
        dotmdcdp: DataTypes.TEXT,
        dotvolume: DataTypes.TEXT,
        dotmc: DataTypes.TEXT,
        dotcs: DataTypes.TEXT,

        xrpcloseprice: DataTypes.STRING,
        xrpudpil: DataTypes.TEXT,
        xrpudpim: DataTypes.TEXT,
        xrpudpis: DataTypes.TEXT,
        xrpmbi: DataTypes.TEXT,
        xrptci: DataTypes.TEXT,
        xrptcicv: DataTypes.TEXT,
        xrpmdccv: DataTypes.TEXT,
        xrpmdcdp: DataTypes.TEXT,
        xrpvolume: DataTypes.TEXT,
        xrpmc: DataTypes.TEXT,
        xrpcs: DataTypes.TEXT,

        linkcloseprice: DataTypes.STRING,
        linkudpil: DataTypes.TEXT,
        linkudpim: DataTypes.TEXT,
        linkudpis: DataTypes.TEXT,
        linkmbi: DataTypes.TEXT,
        linktci: DataTypes.TEXT,
        linktcicv: DataTypes.TEXT,
        linkmdccv: DataTypes.TEXT,
        linkmdcdp: DataTypes.TEXT,
        linkvolume: DataTypes.TEXT,
        linkmc: DataTypes.TEXT,
        linkcs: DataTypes.TEXT,

        atomcloseprice: DataTypes.STRING,
        atomudpil: DataTypes.TEXT,
        atomudpim: DataTypes.TEXT,
        atomudpis: DataTypes.TEXT,
        atommbi: DataTypes.TEXT,
        atomtci: DataTypes.TEXT,
        atomtcicv: DataTypes.TEXT,
        atommdccv: DataTypes.TEXT,
        atommdcdp: DataTypes.TEXT,
        atomvolume: DataTypes.TEXT,
        atommc: DataTypes.TEXT,
        atomcs: DataTypes.TEXT,

        hbarcloseprice: DataTypes.STRING,
        hbarudpil: DataTypes.TEXT,
        hbarudpim: DataTypes.TEXT,
        hbarudpis: DataTypes.TEXT,
        hbarmbi: DataTypes.TEXT,
        hbartci: DataTypes.TEXT,
        hbartcicv: DataTypes.TEXT,
        hbarmdccv: DataTypes.TEXT,
        hbarmdcdp: DataTypes.TEXT,
        hbarvolume: DataTypes.TEXT,
        hbarmc: DataTypes.TEXT,
        hbarcs: DataTypes.TEXT,

        egldcloseprice: DataTypes.STRING,
        egldudpil: DataTypes.TEXT,
        egldudpim: DataTypes.TEXT,
        egldudpis: DataTypes.TEXT,
        egldmbi: DataTypes.TEXT,
        egldtci: DataTypes.TEXT,
        egldtcicv: DataTypes.TEXT,
        egldmdccv: DataTypes.TEXT,
        egldmdcdp: DataTypes.TEXT,
        egldvolume: DataTypes.TEXT,
        egldmc: DataTypes.TEXT,
        egldcs: DataTypes.TEXT,

        vetcloseprice: DataTypes.STRING,
        vetudpil: DataTypes.TEXT,
        vetudpim: DataTypes.TEXT,
        vetudpis: DataTypes.TEXT,
        vetmbi: DataTypes.TEXT,
        vettci: DataTypes.TEXT,
        vettcicv: DataTypes.TEXT,
        vetmdccv: DataTypes.TEXT,
        vetmdcdp: DataTypes.TEXT,
        vetvolume: DataTypes.TEXT,
        vetmc: DataTypes.TEXT,
        vetcs: DataTypes.TEXT,

        algocloseprice: DataTypes.STRING,
        algoudpil: DataTypes.TEXT,
        algoudpim: DataTypes.TEXT,
        algoudpis: DataTypes.TEXT,
        algombi: DataTypes.TEXT,
        algotci: DataTypes.TEXT,
        algotcicv: DataTypes.TEXT,
        algomdccv: DataTypes.TEXT,
        algomdcdp: DataTypes.TEXT,
        algovolume: DataTypes.TEXT,
        algomc: DataTypes.TEXT,
        algocs: DataTypes.TEXT,

        onecloseprice: DataTypes.STRING,
        oneudpil: DataTypes.TEXT,
        oneudpim: DataTypes.TEXT,
        oneudpis: DataTypes.TEXT,
        onembi: DataTypes.TEXT,
        onetci: DataTypes.TEXT,
        onetcicv: DataTypes.TEXT,
        onemdccv: DataTypes.TEXT,
        onemdcdp: DataTypes.TEXT,
        onevolume: DataTypes.TEXT,
        onemc: DataTypes.TEXT,
        onecs: DataTypes.TEXT,

        ftmcloseprice: DataTypes.STRING,
        ftmudpil: DataTypes.TEXT,
        ftmudpim: DataTypes.TEXT,
        ftmudpis: DataTypes.TEXT,
        ftmmbi: DataTypes.TEXT,
        ftmtci: DataTypes.TEXT,
        ftmtcicv: DataTypes.TEXT,
        ftmmdccv: DataTypes.TEXT,
        ftmmdcdp: DataTypes.TEXT,
        ftmvolume: DataTypes.TEXT,
        ftmmc: DataTypes.TEXT,
        ftmcs: DataTypes.TEXT,

        zilcloseprice: DataTypes.STRING,
        ziludpil: DataTypes.TEXT,
        ziludpim: DataTypes.TEXT,
        ziludpis: DataTypes.TEXT,
        zilmbi: DataTypes.TEXT,
        ziltci: DataTypes.TEXT,
        ziltcicv: DataTypes.TEXT,
        zilmdccv: DataTypes.TEXT,
        zilmdcdp: DataTypes.TEXT,
        zilvolume: DataTypes.TEXT,
        zilmc: DataTypes.TEXT,
        zilcs: DataTypes.TEXT,

        ksmcloseprice: DataTypes.STRING,
        ksmudpil: DataTypes.TEXT,
        ksmudpim: DataTypes.TEXT,
        ksmudpis: DataTypes.TEXT,
        ksmmbi: DataTypes.TEXT,
        ksmtci: DataTypes.TEXT,
        ksmtcicv: DataTypes.TEXT,
        ksmmdccv: DataTypes.TEXT,
        ksmmdcdp: DataTypes.TEXT,
        ksmvolume: DataTypes.TEXT,
        ksmmc: DataTypes.TEXT,
        ksmcs: DataTypes.TEXT,

        enjcloseprice: DataTypes.STRING,
        enjudpil: DataTypes.TEXT,
        enjudpim: DataTypes.TEXT,
        enjudpis: DataTypes.TEXT,
        enjmbi: DataTypes.TEXT,
        enjtci: DataTypes.TEXT,
        enjtcicv: DataTypes.TEXT,
        enjmdccv: DataTypes.TEXT,
        enjmdcdp: DataTypes.TEXT,
        enjvolume: DataTypes.TEXT,
        enjmc: DataTypes.TEXT,
        enjcs: DataTypes.TEXT,

        avaxcloseprice: DataTypes.STRING,
        avaxudpil: DataTypes.TEXT,
        avaxudpim: DataTypes.TEXT,
        avaxudpis: DataTypes.TEXT,
        avaxmbi: DataTypes.TEXT,
        avaxtci: DataTypes.TEXT,
        avaxtcicv: DataTypes.TEXT,
        avaxmdccv: DataTypes.TEXT,
        avaxmdcdp: DataTypes.TEXT,
        avaxvolume: DataTypes.TEXT,
        avaxmc: DataTypes.TEXT,
        avaxcs: DataTypes.TEXT,

        maticcloseprice: DataTypes.STRING,
        maticudpil: DataTypes.TEXT,
        maticudpim: DataTypes.TEXT,
        maticudpis: DataTypes.TEXT,
        maticmbi: DataTypes.TEXT,
        matictci: DataTypes.TEXT,
        matictcicv: DataTypes.TEXT,
        maticmdccv: DataTypes.TEXT,
        maticmdcdp: DataTypes.TEXT,
        maticvolume: DataTypes.TEXT,
        maticmc: DataTypes.TEXT,
        maticcs: DataTypes.TEXT,

        bnbcloseprice: DataTypes.STRING,
        bnbudpil: DataTypes.TEXT,
        bnbudpim: DataTypes.TEXT,
        bnbudpis: DataTypes.TEXT,
        bnbmbi: DataTypes.TEXT,
        bnbtci: DataTypes.TEXT,
        bnbtcicv: DataTypes.TEXT,
        bnbmdccv: DataTypes.TEXT,
        bnbmdcdp: DataTypes.TEXT,
        bnbvolume: DataTypes.TEXT,
        bnbmc: DataTypes.TEXT,
        bnbcs: DataTypes.TEXT,

        hntcloseprice: DataTypes.STRING,
        hntudpil: DataTypes.TEXT,
        hntudpim: DataTypes.TEXT,
        hntudpis: DataTypes.TEXT,
        hntmbi: DataTypes.TEXT,
        hnttci: DataTypes.TEXT,
        hnttcicv: DataTypes.TEXT,
        hntmdccv: DataTypes.TEXT,
        hntmdcdp: DataTypes.TEXT,
        hntvolume: DataTypes.TEXT,
        hntmc: DataTypes.TEXT,
        hntcs: DataTypes.TEXT,

        xtzcloseprice: DataTypes.STRING,
        xtzudpil: DataTypes.TEXT,
        xtzudpim: DataTypes.TEXT,
        xtzudpis: DataTypes.TEXT,
        xtzmbi: DataTypes.TEXT,
        xtztci: DataTypes.TEXT,
        xtztcicv: DataTypes.TEXT,
        xtzmdccv: DataTypes.TEXT,
        xtzmdcdp: DataTypes.TEXT,
        xtzvolume: DataTypes.TEXT,
        xtzmc: DataTypes.TEXT,
        xtzcs: DataTypes.TEXT,


        ltccloseprice: DataTypes.STRING,
        ltcudpil: DataTypes.TEXT,
        ltcudpim: DataTypes.TEXT,
        ltcudpis: DataTypes.TEXT,
        ltcmbi: DataTypes.TEXT,
        ltctci: DataTypes.TEXT,
        ltctcicv: DataTypes.TEXT,
        ltcmdccv: DataTypes.TEXT,
        ltcmdcdp: DataTypes.TEXT,
        ltcvolume: DataTypes.TEXT,
        ltcmc: DataTypes.TEXT,
        ltccs: DataTypes.TEXT,


        solcloseprice: DataTypes.STRING,
        soludpil: DataTypes.TEXT,
        soludpim: DataTypes.TEXT,
        soludpis: DataTypes.TEXT,
        solmbi: DataTypes.TEXT,
        soltci: DataTypes.TEXT,
        soltcicv: DataTypes.TEXT,
        solmdccv: DataTypes.TEXT,
        solmdcdp: DataTypes.TEXT,
        solvolume: DataTypes.TEXT,
        solmc: DataTypes.TEXT,
        solcs: DataTypes.TEXT,


        thetacloseprice: DataTypes.STRING,
        thetaudpil: DataTypes.TEXT,
        thetaudpim: DataTypes.TEXT,
        thetaudpis: DataTypes.TEXT,
        thetambi: DataTypes.TEXT,
        thetatci: DataTypes.TEXT,
        thetatcicv: DataTypes.TEXT,
        thetamdccv: DataTypes.TEXT,
        thetamdcdp: DataTypes.TEXT,
        thetavolume: DataTypes.TEXT,
        thetamc: DataTypes.TEXT,
        thetacs: DataTypes.TEXT,


        qntcloseprice: DataTypes.STRING,
        qntudpil: DataTypes.TEXT,
        qntudpim: DataTypes.TEXT,
        qntudpis: DataTypes.TEXT,
        qntmbi: DataTypes.TEXT,
        qnttci: DataTypes.TEXT,
        qnttcicv: DataTypes.TEXT,
        qntmdccv: DataTypes.TEXT,
        qntmdcdp: DataTypes.TEXT,
        qntvolume: DataTypes.TEXT,
        qntmc: DataTypes.TEXT,
        qntcs: DataTypes.TEXT,

        sandcloseprice: DataTypes.STRING,
        sandudpil: DataTypes.TEXT,
        sandudpim: DataTypes.TEXT,
        sandudpis: DataTypes.TEXT,
        sandmbi: DataTypes.TEXT,
        sandtci: DataTypes.TEXT,
        sandtcicv: DataTypes.TEXT,
        sandmdccv: DataTypes.TEXT,
        sandmdcdp: DataTypes.TEXT,
        sandvolume: DataTypes.TEXT,
        sandmc: DataTypes.TEXT,
        sandcs: DataTypes.TEXT,

        nearcloseprice: DataTypes.STRING,
        nearudpil: DataTypes.TEXT,
        nearudpim: DataTypes.TEXT,
        nearudpis: DataTypes.TEXT,
        nearmbi: DataTypes.TEXT,
        neartci: DataTypes.TEXT,
        neartcicv: DataTypes.TEXT,
        nearmdccv: DataTypes.TEXT,
        nearmdcdp: DataTypes.TEXT,
        nearvolume: DataTypes.TEXT,
        nearmc: DataTypes.TEXT,
        nearcs: DataTypes.TEXT,


        udpilavg: DataTypes.TEXT,
        udpimavg: DataTypes.TEXT,
        udpisavg: DataTypes.TEXT,
        mbi: DataTypes.TEXT,
        tcipercent: DataTypes.TEXT,
        mdcpercent: DataTypes.TEXT,
        // aa:DataTypes.STRING,
    },
        {
            sequelize,
            timestamps: false,
            tableName: 'riskdf',
            modelName: 'riskdf',
        });
    return riskdf;
};