'use strict';
const {
    Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
    class riskdf extends Model {
        static associate(models) {
        }
    }
    riskdf.init({
        closetime: DataTypes.DATE,
        btccloseprice: DataTypes.STRING,
        btcudpil: DataTypes.DOUBLE,
        btcudpim: DataTypes.DOUBLE,
        btcudpis: DataTypes.DOUBLE,
        btcmbi: DataTypes.DOUBLE,
        btctci: DataTypes.DOUBLE,
        btctcicv: DataTypes.DOUBLE,
        btcmdccv: DataTypes.DOUBLE,
        btcmdcdp: DataTypes.DOUBLE,
        btcvolume: DataTypes.DOUBLE,
        btcmc: DataTypes.DOUBLE,
        btccs: DataTypes.DOUBLE,

        ethcloseprice: DataTypes.STRING,
        ethudpil: DataTypes.DOUBLE,
        ethudpim: DataTypes.DOUBLE,
        ethudpis: DataTypes.DOUBLE,
        ethmbi: DataTypes.DOUBLE,
        ethtci: DataTypes.DOUBLE,
        ethtcicv: DataTypes.DOUBLE,
        ethmdccv: DataTypes.DOUBLE,
        ethmdcdp: DataTypes.DOUBLE,
        ethvolume: DataTypes.DOUBLE,
        ethmc: DataTypes.DOUBLE,
        ethcs: DataTypes.DOUBLE,

        adacloseprice: DataTypes.STRING,
        adaudpil: DataTypes.DOUBLE,
        adaudpim: DataTypes.DOUBLE,
        adaudpis: DataTypes.DOUBLE,
        adambi: DataTypes.DOUBLE,
        adatci: DataTypes.DOUBLE,
        adatcicv: DataTypes.DOUBLE,
        adamdccv: DataTypes.DOUBLE,
        adamdcdp: DataTypes.DOUBLE,
        adavolume: DataTypes.DOUBLE,
        adamc: DataTypes.DOUBLE,
        adacs: DataTypes.DOUBLE,

        dotcloseprice: DataTypes.STRING,
        dotudpil: DataTypes.DOUBLE,
        dotudpim: DataTypes.DOUBLE,
        dotudpis: DataTypes.DOUBLE,
        dotmbi: DataTypes.DOUBLE,
        dottci: DataTypes.DOUBLE,
        dottcicv: DataTypes.DOUBLE,
        dotmdccv: DataTypes.DOUBLE,
        dotmdcdp: DataTypes.DOUBLE,
        dotvolume: DataTypes.DOUBLE,
        dotmc: DataTypes.DOUBLE,
        dotcs: DataTypes.DOUBLE,

        xrpcloseprice: DataTypes.STRING,
        xrpudpil: DataTypes.DOUBLE,
        xrpudpim: DataTypes.DOUBLE,
        xrpudpis: DataTypes.DOUBLE,
        xrpmbi: DataTypes.DOUBLE,
        xrptci: DataTypes.DOUBLE,
        xrptcicv: DataTypes.DOUBLE,
        xrpmdccv: DataTypes.DOUBLE,
        xrpmdcdp: DataTypes.DOUBLE,
        xrpvolume: DataTypes.DOUBLE,
        xrpmc: DataTypes.DOUBLE,
        xrpcs: DataTypes.DOUBLE,

        linkcloseprice: DataTypes.STRING,
        linkudpil: DataTypes.DOUBLE,
        linkudpim: DataTypes.DOUBLE,
        linkudpis: DataTypes.DOUBLE,
        linkmbi: DataTypes.DOUBLE,
        linktci: DataTypes.DOUBLE,
        linktcicv: DataTypes.DOUBLE,
        linkmdccv: DataTypes.DOUBLE,
        linkmdcdp: DataTypes.DOUBLE,
        linkvolume: DataTypes.DOUBLE,
        linkmc: DataTypes.DOUBLE,
        linkcs: DataTypes.DOUBLE,

        atomcloseprice: DataTypes.STRING,
        atomudpil: DataTypes.DOUBLE,
        atomudpim: DataTypes.DOUBLE,
        atomudpis: DataTypes.DOUBLE,
        atommbi: DataTypes.DOUBLE,
        atomtci: DataTypes.DOUBLE,
        atomtcicv: DataTypes.DOUBLE,
        atommdccv: DataTypes.DOUBLE,
        atommdcdp: DataTypes.DOUBLE,
        atomvolume: DataTypes.DOUBLE,
        atommc: DataTypes.DOUBLE,
        atomcs: DataTypes.DOUBLE,

        hbarcloseprice: DataTypes.STRING,
        hbarudpil: DataTypes.DOUBLE,
        hbarudpim: DataTypes.DOUBLE,
        hbarudpis: DataTypes.DOUBLE,
        hbarmbi: DataTypes.DOUBLE,
        hbartci: DataTypes.DOUBLE,
        hbartcicv: DataTypes.DOUBLE,
        hbarmdccv: DataTypes.DOUBLE,
        hbarmdcdp: DataTypes.DOUBLE,
        hbarvolume: DataTypes.DOUBLE,
        hbarmc: DataTypes.DOUBLE,
        hbarcs: DataTypes.DOUBLE,

        egldcloseprice: DataTypes.STRING,
        egldudpil: DataTypes.DOUBLE,
        egldudpim: DataTypes.DOUBLE,
        egldudpis: DataTypes.DOUBLE,
        egldmbi: DataTypes.DOUBLE,
        egldtci: DataTypes.DOUBLE,
        egldtcicv: DataTypes.DOUBLE,
        egldmdccv: DataTypes.DOUBLE,
        egldmdcdp: DataTypes.DOUBLE,
        egldvolume: DataTypes.DOUBLE,
        egldmc: DataTypes.DOUBLE,
        egldcs: DataTypes.DOUBLE,

        vetcloseprice: DataTypes.STRING,
        vetudpil: DataTypes.DOUBLE,
        vetudpim: DataTypes.DOUBLE,
        vetudpis: DataTypes.DOUBLE,
        vetmbi: DataTypes.DOUBLE,
        vettci: DataTypes.DOUBLE,
        vettcicv: DataTypes.DOUBLE,
        vetmdccv: DataTypes.DOUBLE,
        vetmdcdp: DataTypes.DOUBLE,
        vetvolume: DataTypes.DOUBLE,
        vetmc: DataTypes.DOUBLE,
        vetcs: DataTypes.DOUBLE,

        algocloseprice: DataTypes.STRING,
        algoudpil: DataTypes.DOUBLE,
        algoudpim: DataTypes.DOUBLE,
        algoudpis: DataTypes.DOUBLE,
        algombi: DataTypes.DOUBLE,
        algotci: DataTypes.DOUBLE,
        algotcicv: DataTypes.DOUBLE,
        algomdccv: DataTypes.DOUBLE,
        algomdcdp: DataTypes.DOUBLE,
        algovolume: DataTypes.DOUBLE,
        algomc: DataTypes.DOUBLE,
        algocs: DataTypes.DOUBLE,

        onecloseprice: DataTypes.STRING,
        oneudpil: DataTypes.DOUBLE,
        oneudpim: DataTypes.DOUBLE,
        oneudpis: DataTypes.DOUBLE,
        onembi: DataTypes.DOUBLE,
        onetci: DataTypes.DOUBLE,
        onetcicv: DataTypes.DOUBLE,
        onemdccv: DataTypes.DOUBLE,
        onemdcdp: DataTypes.DOUBLE,
        onevolume: DataTypes.DOUBLE,
        onemc: DataTypes.DOUBLE,
        onecs: DataTypes.DOUBLE,

        ftmcloseprice: DataTypes.STRING,
        ftmudpil: DataTypes.DOUBLE,
        ftmudpim: DataTypes.DOUBLE,
        ftmudpis: DataTypes.DOUBLE,
        ftmmbi: DataTypes.DOUBLE,
        ftmtci: DataTypes.DOUBLE,
        ftmtcicv: DataTypes.DOUBLE,
        ftmmdccv: DataTypes.DOUBLE,
        ftmmdcdp: DataTypes.DOUBLE,
        ftmvolume: DataTypes.DOUBLE,
        ftmmc: DataTypes.DOUBLE,
        ftmcs: DataTypes.DOUBLE,

        zilcloseprice: DataTypes.STRING,
        ziludpil: DataTypes.DOUBLE,
        ziludpim: DataTypes.DOUBLE,
        ziludpis: DataTypes.DOUBLE,
        zilmbi: DataTypes.DOUBLE,
        ziltci: DataTypes.DOUBLE,
        ziltcicv: DataTypes.DOUBLE,
        zilmdccv: DataTypes.DOUBLE,
        zilmdcdp: DataTypes.DOUBLE,
        zilvolume: DataTypes.DOUBLE,
        zilmc: DataTypes.DOUBLE,
        zilcs: DataTypes.DOUBLE,

        ksmcloseprice: DataTypes.STRING,
        ksmudpil: DataTypes.DOUBLE,
        ksmudpim: DataTypes.DOUBLE,
        ksmudpis: DataTypes.DOUBLE,
        ksmmbi: DataTypes.DOUBLE,
        ksmtci: DataTypes.DOUBLE,
        ksmtcicv: DataTypes.DOUBLE,
        ksmmdccv: DataTypes.DOUBLE,
        ksmmdcdp: DataTypes.DOUBLE,
        ksmvolume: DataTypes.DOUBLE,
        ksmmc: DataTypes.DOUBLE,
        ksmcs: DataTypes.DOUBLE,

        enjcloseprice: DataTypes.STRING,
        enjudpil: DataTypes.DOUBLE,
        enjudpim: DataTypes.DOUBLE,
        enjudpis: DataTypes.DOUBLE,
        enjmbi: DataTypes.DOUBLE,
        enjtci: DataTypes.DOUBLE,
        enjtcicv: DataTypes.DOUBLE,
        enjmdccv: DataTypes.DOUBLE,
        enjmdcdp: DataTypes.DOUBLE,
        enjvolume: DataTypes.DOUBLE,
        enjmc: DataTypes.DOUBLE,
        enjcs: DataTypes.DOUBLE,

        avaxcloseprice: DataTypes.STRING,
        avaxudpil: DataTypes.DOUBLE,
        avaxudpim: DataTypes.DOUBLE,
        avaxudpis: DataTypes.DOUBLE,
        avaxmbi: DataTypes.DOUBLE,
        avaxtci: DataTypes.DOUBLE,
        avaxtcicv: DataTypes.DOUBLE,
        avaxmdccv: DataTypes.DOUBLE,
        avaxmdcdp: DataTypes.DOUBLE,
        avaxvolume: DataTypes.DOUBLE,
        avaxmc: DataTypes.DOUBLE,
        avaxcs: DataTypes.DOUBLE,

        maticcloseprice: DataTypes.STRING,
        maticudpil: DataTypes.DOUBLE,
        maticudpim: DataTypes.DOUBLE,
        maticudpis: DataTypes.DOUBLE,
        maticmbi: DataTypes.DOUBLE,
        matictci: DataTypes.DOUBLE,
        matictcicv: DataTypes.DOUBLE,
        maticmdccv: DataTypes.DOUBLE,
        maticmdcdp: DataTypes.DOUBLE,
        maticvolume: DataTypes.DOUBLE,
        maticmc: DataTypes.DOUBLE,
        maticcs: DataTypes.DOUBLE,

        bnbcloseprice: DataTypes.STRING,
        bnbudpil: DataTypes.DOUBLE,
        bnbudpim: DataTypes.DOUBLE,
        bnbudpis: DataTypes.DOUBLE,
        bnbmbi: DataTypes.DOUBLE,
        bnbtci: DataTypes.DOUBLE,
        bnbtcicv: DataTypes.DOUBLE,
        bnbmdccv: DataTypes.DOUBLE,
        bnbmdcdp: DataTypes.DOUBLE,
        bnbvolume: DataTypes.DOUBLE,
        bnbmc: DataTypes.DOUBLE,
        bnbcs: DataTypes.DOUBLE,

        hntcloseprice: DataTypes.STRING,
        hntudpil: DataTypes.DOUBLE,
        hntudpim: DataTypes.DOUBLE,
        hntudpis: DataTypes.DOUBLE,
        hntmbi: DataTypes.DOUBLE,
        hnttci: DataTypes.DOUBLE,
        hnttcicv: DataTypes.DOUBLE,
        hntmdccv: DataTypes.DOUBLE,
        hntmdcdp: DataTypes.DOUBLE,
        hntvolume: DataTypes.DOUBLE,
        hntmc: DataTypes.DOUBLE,
        hntcs: DataTypes.DOUBLE,

        xtzcloseprice: DataTypes.STRING,
        xtzudpil: DataTypes.DOUBLE,
        xtzudpim: DataTypes.DOUBLE,
        xtzudpis: DataTypes.DOUBLE,
        xtzmbi: DataTypes.DOUBLE,
        xtztci: DataTypes.DOUBLE,
        xtztcicv: DataTypes.DOUBLE,
        xtzmdccv: DataTypes.DOUBLE,
        xtzmdcdp: DataTypes.DOUBLE,
        xtzvolume: DataTypes.DOUBLE,
        xtzmc: DataTypes.DOUBLE,
        xtzcs: DataTypes.DOUBLE,


        ltccloseprice: DataTypes.STRING,
        ltcudpil: DataTypes.DOUBLE,
        ltcudpim: DataTypes.DOUBLE,
        ltcudpis: DataTypes.DOUBLE,
        ltcmbi: DataTypes.DOUBLE,
        ltctci: DataTypes.DOUBLE,
        ltctcicv: DataTypes.DOUBLE,
        ltcmdccv: DataTypes.DOUBLE,
        ltcmdcdp: DataTypes.DOUBLE,
        ltcvolume: DataTypes.DOUBLE,
        ltcmc: DataTypes.DOUBLE,
        ltccs: DataTypes.DOUBLE,


        solcloseprice: DataTypes.STRING,
        soludpil: DataTypes.DOUBLE,
        soludpim: DataTypes.DOUBLE,
        soludpis: DataTypes.DOUBLE,
        solmbi: DataTypes.DOUBLE,
        soltci: DataTypes.DOUBLE,
        soltcicv: DataTypes.DOUBLE,
        solmdccv: DataTypes.DOUBLE,
        solmdcdp: DataTypes.DOUBLE,
        solvolume: DataTypes.DOUBLE,
        solmc: DataTypes.DOUBLE,
        solcs: DataTypes.DOUBLE,


        thetacloseprice: DataTypes.STRING,
        thetaudpil: DataTypes.DOUBLE,
        thetaudpim: DataTypes.DOUBLE,
        thetaudpis: DataTypes.DOUBLE,
        thetambi: DataTypes.DOUBLE,
        thetatci: DataTypes.DOUBLE,
        thetatcicv: DataTypes.DOUBLE,
        thetamdccv: DataTypes.DOUBLE,
        thetamdcdp: DataTypes.DOUBLE,
        thetavolume: DataTypes.DOUBLE,
        thetamc: DataTypes.DOUBLE,
        thetacs: DataTypes.DOUBLE,


        qntcloseprice: DataTypes.STRING,
        qntudpil: DataTypes.DOUBLE,
        qntudpim: DataTypes.DOUBLE,
        qntudpis: DataTypes.DOUBLE,
        qntmbi: DataTypes.DOUBLE,
        qnttci: DataTypes.DOUBLE,
        qnttcicv: DataTypes.DOUBLE,
        qntmdccv: DataTypes.DOUBLE,
        qntmdcdp: DataTypes.DOUBLE,
        qntvolume: DataTypes.DOUBLE,
        qntmc: DataTypes.DOUBLE,
        qntcs: DataTypes.DOUBLE,

        sandcloseprice: DataTypes.STRING,
        sandudpil: DataTypes.DOUBLE,
        sandudpim: DataTypes.DOUBLE,
        sandudpis: DataTypes.DOUBLE,
        sandmbi: DataTypes.DOUBLE,
        sandtci: DataTypes.DOUBLE,
        sandtcicv: DataTypes.DOUBLE,
        sandmdccv: DataTypes.DOUBLE,
        sandmdcdp: DataTypes.DOUBLE,
        sandvolume: DataTypes.DOUBLE,
        sandmc: DataTypes.DOUBLE,
        sandcs: DataTypes.DOUBLE,

        nearcloseprice: DataTypes.STRING,
        nearudpil: DataTypes.DOUBLE,
        nearudpim: DataTypes.DOUBLE,
        nearudpis: DataTypes.DOUBLE,
        nearmbi: DataTypes.DOUBLE,
        neartci: DataTypes.DOUBLE,
        neartcicv: DataTypes.DOUBLE,
        nearmdccv: DataTypes.DOUBLE,
        nearmdcdp: DataTypes.DOUBLE,
        nearvolume: DataTypes.DOUBLE,
        nearmc: DataTypes.DOUBLE,
        nearcs: DataTypes.DOUBLE,


        udpilavg: DataTypes.DOUBLE,
        udpimavg: DataTypes.DOUBLE,
        udpisavg: DataTypes.DOUBLE,
        mbi: DataTypes.DOUBLE,
        tcipercent: DataTypes.DOUBLE,
        mdcpercent: DataTypes.DOUBLE,
        // aa:DataTypes.STRING,
    },
        {
            sequelize,
            timestamps: false,
            tableName: 'riskdf',
            modelName: 'riskdf',
        });
    return riskdf;
};